language: node_js
node_js:
  - "8.11.4"
before_script:
  - npm i --ignore-scripts
  - npm run build:spec
  - psql -c 'create database testdb;' -U postgres
  - cp local.config.travis.json local.config.json
services:
  - postgresql 