language: node_js
node_js:
  - "10.13.0"
before_script:
  - psql -c 'create database testdb;' -U postgres
  - cp local.config.travis.json local.config.json
install:
  - npm install --ignore-scripts
services:
  - postgresql 
after_success:
  - npm run coveralls