language: node_js
node_js:
  - 16
before_script:
  - psql -c 'create database testdb;' -U postgres
  - cp .env.travis .env
install:
	- npm install --ignore-scripts
services:
	- postgresql
after_success:
  - npm run coveralls
